import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const roboto = Roboto({
  
  subsets: ["latin"],
});



export const metadata = {
  title: "PennyWise",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body
        className={roboto.className}
      >
        <Header/>
        <main className="min-h-screen">{children}</main>
        <Footer/>
      </body>
    </html>

    </ClerkProvider>
    
  );
}
