import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const roboto = Roboto({
  
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
  display: "swap",
});



export const metadata = {
  title: "PennyWise",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body
        className={roboto.className}
      >
        <Header/>
        <main className="min-h-screen">{children}</main>
        <Toaster richColors/>
        <Footer/>
      </body>
    </html>

    </ClerkProvider>
    
  );
}
